# Generated by Django 4.1.1 on 2022-09-26 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_todo_options_rename_owner_todo_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='todo',
            name='state',
            field=models.CharField(max_length=100),
        ),
    ]
