# Generated by Django 4.1.1 on 2022-09-27 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_todo_name_alter_todo_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='state',
            field=models.CharField(choices=[('Todo', 'Todo'), ('In Progress', 'In Progress'), ('In Review', 'In Review'), ('Done', 'Done')], max_length=100),
        ),
    ]
